server:
  port: 9004

spring:
  redis:
    cluster:
      nodes:  192.168.68.107:6379, 192.168.68.107:6380, 192.168.68.107:6381
      max-redirects: 2


#For master slave Configuration
redis:
  master:
    host: 192.168.68.107
    port: 6379
  slaves:
    - host: 192.168.68.107
      port: 16379
    - host: 192.168.68.107
      port: 26379


#host:
#  redis: localhost
#
#port:
#  redis: 6379
#
stream:
  key: email-events