server:
  port: 9004

spring:
  redis:
    cluster:
      nodes:  192.168.68.107:6379, 192.168.68.107:6380, 192.168.68.107:6381
      max-redirects: 2



#host:
#  redis: localhost
#
#port:
#  redis: 6379
#
stream:
  key: email-events